services:
  user-service:
    build: ./Microservices/user-service
    container_name: user-service
    ports:
      - "3000:3000"
    networks:
      - microservices-net

  product-service:
    build: ./Microservices/product-service
    container_name: product-service
    ports:
      - "3001:3001"
    networks:
      - microservices-net

  gateway-service:
    build: ./Microservices/gateway-service
    container_name: gateway-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge